service: testMELI
frameworkVersion: '2'

provider:
  name: aws
  runtime: nodejs12.x


functions:
  hello:
    handler: './lambdas/handlers/app/mutants/index.handler'
    events:
      - http:
          method: post
          path: mutant
plugins:
  - serverless-offline
  - serverless-plugin-typescript